// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proj.Repository.Data;

namespace Proj.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Proj.Domain.Entities.ContaRestaurante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataAlmoco");

                    b.Property<DateTime>("dataPagamento");

                    b.Property<int>("idrestaurante");

                    b.Property<int?>("restauranteid");

                    b.Property<int>("kgGasto");

                    b.Property<double>("mediaConsumo");

                    b.Property<double>("valorAPagar");

                    b.HasKey("id");

                    b.HasIndex("restauranteid");

                    b.ToTable("ContasRestaurante");
                });

            modelBuilder.Entity("Proj.Domain.Entities.Restaurante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("bairro");

                    b.Property<string>("cidade");

                    b.Property<string>("estado");

                    b.Property<string>("id");

                    b.Property<string>("numero");

                    b.HasKey("id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Proj.Domain.Entities.ContaRestaurante", b =>
                {
                    b.HasOne("Proj.Domain.Entities.Restaurante", "restaurante")
                        .WithMany("contasRestaurante")
                        .HasForeignKey("restaurente")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
